### ISSUE TITLE
Change Github Project Description

### ISSUE THREAD

**Issue by Saad-Mahamood** [lambdahands/lingo#1]
Hello,

I came across your project and was wondering if it would be possible to amend the Github project description:

> A Clojure natural language generator built on top of Google’s simplenlg library.

To:

> A Clojure natural language generator built on top of University of Aberdeen’s SimpleNLG library.

Since SimpleNLG is owned by the University of Aberdeen and is hosted on Github now: https://github.com/simplenlg/simplenlg

**Comment by lambdahands** [comment]
Hey, sorry this has been a while since going through this repo. Happy to change the description!

**Comment by Saad-Mahamood** [comment]
Thanks! :)
